apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        # Chú ý: Biến ${IMAGE_TAG} sẽ được GitHub Actions tự động thay thế
        image: ${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # Luôn phải có giới hạn tài nguyên để K8s schedule Pod chuẩn xác, tránh memory leak
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"